//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPapurri
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class herbalEntities : DbContext
    {
        public herbalEntities()
            : base("name=herbalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Estado_Producto> Estado_Producto { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Subproducto> Subproductoes { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
    }
}
