//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPapurri.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subproducto
    {
        public int id_sprod { get; set; }
        public int id_producto { get; set; }
        public int id_cliente { get; set; }
        public string formato { get; set; }
        public int id_estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estado_Producto Estado_Producto { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
