//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPapurri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subproducto
    {
        public int id_sprod { get; set; }
        public int id_producto { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
